organization: mattermost # org name on holopin
defaultSticker: clul38u2n156490gl8ti3srnek # sticker ID for "Mattermost QA Community Contributors", can be changed in the future
stickers:
  - id: clul38u2n156490gl8ti3srnek # sticker id
    alias: Mattermost QA Community Contributors # shorthand-string
